In [9]:
import torch

# Original matrix provided by the user
matrix = torch.tensor([
[1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	0E+00],
[0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00],
[0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00	,1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00],
[0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00	,1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	1E+00,	0E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00	,0E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	0E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00	,1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	1E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00	,1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00	,1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	1E+00,	0E+00,	0E+00,	1E+00,	0E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00	,0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	0E+00,	1E+00,	1E+00	,1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	0E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	1E+00,	0E+00	,0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00],
[0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	0E+00,	1E+00,	0E+00,	1E+00	,0E+00,	1E+00,	1E+00,	0E+00,	0E+00,	1E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00,	1E+00,	1E+00,	1E+00,	0E+00,	1E+00,	0E+00,	1E+00,	1E+00,	1E+00]

], dtype=torch.int)


# Compute the transpose of the matrix
transposed_matrix = matrix.t()

transposed_matrix


/var/folders/71/hry96qw555j_rlvg3tfgrh180000gn/T/ipykernel_49366/2632488042.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  matrix = torch.tensor([


tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        [1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1],
        [1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 1

In [13]:
import numpy as np

# Define dimensions
k, n = 10, 26
r = n - k

# Construct G
G_identity = np.eye(k, dtype=int)
G_parity = np.random.randint(0, 2, size=(k, r))
G = np.hstack((G_identity, G_parity))

# # Construct H by finding nullspace of G
# H = np.linalg.null_space(G.T)

G


(array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
         1, 1, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
         1, 0, 1, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
         0, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
         0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
         1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
         0, 1, 0, 1]]),
 tensor([[1., 0., 1., 0., 0.

In [15]:
import torch
bits = 10
encoded = 26
test1 = 10 * torch.log10(torch.tensor(bits / encoded, dtype=torch.float)) 
test1 = test1 - torch.tensor(10/26)

print("test1", test1)

test1 tensor(-4.5343)


In [16]:
import bchlib
help(bchlib)

Help on module BCH:

NAME
    BCH - BCH Library

CLASSES
    builtins.object
        bchlib.BCH
    
    class BCH(builtins.object)
     |  BCH Encoder/Decoder
     |  
     |  __init__(t, poly=None, m=None, swap_bits=False) → bch
     |      Constructor creates a BCH object with given 't' bit strength.  At
     |      least one of 'poly' and/or 'm' must be provided.  If 'poly' is
     |      provided but 'm' (Galois field order) is not, 'm' will be
     |      calculated automatically.  If 'm' between 5 and 15 inclusive is'
     |      provided, 'polywill be selected automatically.  The 'swap_bits'
     |      parameter will reverse the bit order within data and syndrome
     |      bytes.
     |  
     |  Methods defined here:
     |  
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |  
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  compute_even_syn(...)
     |

In [36]:
import torch
n = 3
model = torch.load(f'Hamming74/Result/Model/SLNN_CPU/SLNN_model_hiddenlayer{n}_BER0.pth')
print(model)

OrderedDict([('hidden.weight', tensor([[ 0.3186, -0.7587,  0.3499, -0.0264,  0.4231, -0.0029, -0.4470],
        [-0.5340, -0.4924,  0.1587, -0.5130, -0.5120,  0.0723,  0.0522],
        [ 0.4094, -0.0160, -0.4631, -0.7529,  0.3200,  0.0030,  0.3455]])), ('hidden.bias', tensor([2.7576, 2.8162, 2.7779])), ('output.weight', tensor([[ 0.0523,  1.9449,  0.3187],
        [-1.6196, -1.1628,  0.2580],
        [-1.4542, -0.0633, -1.2081],
        [-0.1327,  1.0619,  1.8904],
        [ 1.5175, -1.2796,  0.2381],
        [-1.5125, -0.0163,  1.5253],
        [ 0.0256, -1.1797,  1.7432],
        [-0.0029,  0.1037,  0.1355],
        [-0.0391,  0.0118,  0.1176],
        [-0.0166,  1.2566, -1.4628],
        [ 1.3978,  0.0046, -1.1620],
        [-1.6031,  1.4161, -0.0148],
        [ 0.0822, -0.9602, -1.5811],
        [ 1.3848,  0.1911,  1.4653],
        [ 1.5415,  1.2094,  0.1087],
        [-0.1495, -1.8845, -0.0965]])), ('output.bias', tensor([-6.1831,  7.2489,  7.7801, -7.6086, -1.2018,  0.0105, -1.38