In [1]:
import torch

# Original matrix provided by the user
matrix = torch.tensor([[1, 1, 1, 1, 0, 1, 1],
                         [0, 0, 1, 0, 1, 0, 1],
                         [1, 1, 1, 1, 1, 1, 1],
                         [1, 1, 1, 0, 1, 1, 1],
                         [1, 1, 1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1, 1, 1],], dtype=torch.int)


# Compute the transpose of the matrix
transposed_matrix = matrix.t()

transposed_matrix


tensor([[1, 0, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 0, 1, 1, 1],
        [0, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [13]:
import numpy as np

# Define dimensions
k, n = 10, 26
r = n - k

# Construct G
G_identity = np.eye(k, dtype=int)
G_parity = np.random.randint(0, 2, size=(k, r))
G = np.hstack((G_identity, G_parity))

# # Construct H by finding nullspace of G
# H = np.linalg.null_space(G.T)

G


(array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
         1, 1, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
         1, 0, 1, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
         0, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
         0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
         1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
         0, 1, 0, 1]]),
 tensor([[1., 0., 1., 0., 0.

In [2]:
import torch

# Your first tensor
tensor1 = torch.tensor([[0.1582, 0.2170, 0.1495, 0.3974, 0.4741, 0.2054, 0.7275],
                        [0.8117, 0.4013, 0.1386, 0.2082, 0.2137, 0.1977, 0.0406]])

# Your second tensor, which seems to be intended as a per-column property
tensor2 = torch.tensor([2.3291, 2.0119])

# Reshape tensor2 from [2] to [1, 2] for proper broadcasting
tensor2_reshaped = tensor2.view(1, -1)

# Broadcast tensor2 across the rows of tensor1 and perform element-wise division
# Note: tensor1 needs to be divided in a manner that matches your description, which seems to have a misunderstanding.
# If you intend to divide each column by a single value, tensor2 should represent a value per column, not per row.
# Assuming a correction, where tensor2 represents column-wise properties and has shape [7], here's a corrected approach:

# Corrected tensor2 for column-wise properties
# tensor2_corrected = torch.tensor([2.3291, 2.0119])  # Placeholder, replace with actual column-wise values

# Perform the division
result = tensor1 / tensor2_reshaped

print("Resulting Tensor:\n", result)


RuntimeError: The size of tensor a (7) must match the size of tensor b (2) at non-singleton dimension 1

In [13]:
threshold = torch.arange(0, 0.9, 0.001)
print(threshold)

tensor([0.0000, 0.0010, 0.0020, 0.0030, 0.0040, 0.0050, 0.0060, 0.0070, 0.0080,
        0.0090, 0.0100, 0.0110, 0.0120, 0.0130, 0.0140, 0.0150, 0.0160, 0.0170,
        0.0180, 0.0190, 0.0200, 0.0210, 0.0220, 0.0230, 0.0240, 0.0250, 0.0260,
        0.0270, 0.0280, 0.0290, 0.0300, 0.0310, 0.0320, 0.0330, 0.0340, 0.0350,
        0.0360, 0.0370, 0.0380, 0.0390, 0.0400, 0.0410, 0.0420, 0.0430, 0.0440,
        0.0450, 0.0460, 0.0470, 0.0480, 0.0490, 0.0500, 0.0510, 0.0520, 0.0530,
        0.0540, 0.0550, 0.0560, 0.0570, 0.0580, 0.0590, 0.0600, 0.0610, 0.0620,
        0.0630, 0.0640, 0.0650, 0.0660, 0.0670, 0.0680, 0.0690, 0.0700, 0.0710,
        0.0720, 0.0730, 0.0740, 0.0750, 0.0760, 0.0770, 0.0780, 0.0790, 0.0800,
        0.0810, 0.0820, 0.0830, 0.0840, 0.0850, 0.0860, 0.0870, 0.0880, 0.0890,
        0.0900, 0.0910, 0.0920, 0.0930, 0.0940, 0.0950, 0.0960, 0.0970, 0.0980,
        0.0990, 0.1000, 0.1010, 0.1020, 0.1030, 0.1040, 0.1050, 0.1060, 0.1070,
        0.1080, 0.1090, 0.1100, 0.1110, 

In [41]:
import torch
threshold = 39
# modified_model_pth = f"Hamming74/Result/Model/SLNN_decrease_hidden.weight_cpu/SLNN_model_hiddenlayer{threshold}_BER0.pth"
modified_model_pth = f"Hamming74/Result/Model/SLNN_modified_neuron7_cpu_hidden.weight/SLNN_model_modified_hiddenlayer7_threshold{threshold}_BER0.pth"
print("modified model:", torch.load(modified_model_pth))

modified model: OrderedDict([('hidden.weight', tensor([[ 0.0000,  0.0000,  0.7195,  0.0000,  0.0000,  0.7038,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.7659,  0.0000,  0.7190,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -1.1143,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.8998],
        [ 0.0000,  1.2054,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.6529,  0.0000,  0.6603,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.6563,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])), ('hidden.bias', tensor([2.5140, 2.6826, 2.6397, 2.6925, 2.5278, 2.5654, 2.7825])), ('output.weight', tensor([[-0.9320, -1.2707,  1.1320,  1.0465, -0.8846, -0.6712,  0.6520],
        [-1.0896,  0.8015,  0.9044,  0.2587,  0.7822,  0.9356, -1.4586],
        [-0.8282,  0.9302, -0.0997,  0.9627,  1.0229, -0.7685,  1.1151],
        [ 0.8348,  0.7909,  0.9691,  0.4444, -1.1093, -0.9300, -1.3207],
        [-0.9278, -0.3306, -1.2269,  1.3560, -

In [42]:
import torch

# Your input tensor
input_tensor = torch.tensor([[ 0.0000,  0.0000,  0.7195,  0.0000,  0.0000,  0.7038,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.7659,  0.0000,  0.7190,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -1.1143,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.8998],
        [ 0.0000,  1.2054,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.6529,  0.0000,  0.6603,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.6563,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

# Apply thresholding operation
output_tensor = torch.where(input_tensor != 0, torch.tensor(1), torch.tensor(0))
print(output_tensor)

tensor([[0, 0, 1, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]])


In [47]:
import torch

# 定义张量
tensor = torch.tensor([
        0.2013, 0.0217, 0.2494, 0.1773, 0.0606, 0.2440, 0.0456,
        0.0653, 0.0180, 0.0329, 0.2949, 0.1801, 0.2768, 0.1321,
        0.0356, 0.0377, 0.0550, 0.1136, 0.4752, 0.1485, 0.1345,
        0.2090, 0.0122, 0.1893, 0.0160, 0.1579, 0.0372, 0.3784,
        0.0110, 0.6724, 0.0755, 0.0725, 0.0762, 0.0408, 0.0517,
        0.2451, 0.0163, 0.2479, 0.2282, 0.0336, 0.2057, 0.0232,
        0.2293, 0.0324, 0.1897, 0.1027, 0.1369, 0.0909, 0.2181,
        0.0005, 0.0008, 0.0034, 0.0167, 0.0174, 0.0194, 0.0415, 0.0474, 0.0501,
        0.0502, 0.0533, 0.0643, 0.0695, 0.0896, 0.0908, 0.0936, 0.0947, 0.0982,
        0.0989, 0.1019, 0.1092, 0.1136, 0.1149, 0.1179, 0.1209, 0.1230, 0.1236,
        0.1255, 0.1286, 0.1299, 0.1303, 0.1304, 0.1320, 0.1325, 0.1335, 0.1342,
        0.1342, 0.1346, 0.1377, 0.1385, 0.1405, 0.1407, 0.1407, 0.1411, 0.1415,
        0.1415, 0.1419, 0.1430, 0.1431, 0.1446, 0.1451, 0.1453, 0.1460, 0.1482,
        0.1486, 0.1501, 0.1502, 0.1509, 0.1514, 0.1518, 0.1520, 0.1559, 0.1559,
        0.1560, 0.1585, 0.1588, 0.1594, 0.1610, 0.1624, 0.1626, 0.1634, 0.1638,
        0.1646, 0.1655, 0.1656, 0.1659, 0.1665, 0.1681, 0.1684, 0.1684, 0.1687,
        0.1705, 0.1708, 0.1715, 0.1718, 0.1731, 0.1731, 0.1733, 0.1749, 0.1750,
        0.1786, 0.1799, 0.1824, 0.1841, 0.1860, 0.1871, 0.1883, 0.1891, 0.1925,
        0.1929, 0.1938, 0.1946, 0.1947, 0.1969, 0.2056, 0.2064, 0.2126, 0.2265,
        0.2341, 0.2396, 0.2453, 0.2698
])

sorted_tensor, indices = tensor.sort()

sorted_tensor

tensor([5.0000e-04, 8.0000e-04, 3.4000e-03, 1.1000e-02, 1.2200e-02, 1.6000e-02,
        1.6300e-02, 1.6700e-02, 1.7400e-02, 1.8000e-02, 1.9400e-02, 2.1700e-02,
        2.3200e-02, 3.2400e-02, 3.2900e-02, 3.3600e-02, 3.5600e-02, 3.7200e-02,
        3.7700e-02, 4.0800e-02, 4.1500e-02, 4.5600e-02, 4.7400e-02, 5.0100e-02,
        5.0200e-02, 5.1700e-02, 5.3300e-02, 5.5000e-02, 6.0600e-02, 6.4300e-02,
        6.5300e-02, 6.9500e-02, 7.2500e-02, 7.5500e-02, 7.6200e-02, 8.9600e-02,
        9.0800e-02, 9.0900e-02, 9.3600e-02, 9.4700e-02, 9.8200e-02, 9.8900e-02,
        1.0190e-01, 1.0270e-01, 1.0920e-01, 1.1360e-01, 1.1360e-01, 1.1490e-01,
        1.1790e-01, 1.2090e-01, 1.2300e-01, 1.2360e-01, 1.2550e-01, 1.2860e-01,
        1.2990e-01, 1.3030e-01, 1.3040e-01, 1.3200e-01, 1.3210e-01, 1.3250e-01,
        1.3350e-01, 1.3420e-01, 1.3420e-01, 1.3450e-01, 1.3460e-01, 1.3690e-01,
        1.3770e-01, 1.3850e-01, 1.4050e-01, 1.4070e-01, 1.4070e-01, 1.4110e-01,
        1.4150e-01, 1.4150e-01, 1.4190e-

In [11]:
# 数据列表
data = [[ 0.5807,  0.0000,  0.7195, -0.5115, -0.1748,  0.7038, -0.1317],
        [ 0.1696,  0.0000, -0.0854,  0.7659, -0.4676,  0.7190,  0.3430],
        [ 0.0835,  0.0884,  0.1289, -0.2663, -1.1143, -0.3482,  0.3153],
        [ 0.4970,  0.0000, -0.4501,  0.0000, -0.3754,  0.0885, -0.8998],
        [ 0.0000,  1.2054,  0.1353,  0.1299, -0.1366,  0.0732, -0.0926],
        [ 0.6529,  0.0000,  0.6603,  0.6080, -0.0896, -0.5479,  0.0000],
        [-0.6563, -0.0928,  0.5427,  0.2940, -0.3917,  0.2601, -0.6240]]

# 生成 LaTeX 代码
latex_code = "\\begin{table}[htbp]\n" \
             "    \\centering\n" \
             "    \\begin{tabular}{|c|c|c|c|c|c|c|c|}\n" \
             "        \\hline\n" \
             "        \\textbf{Input Layer Neurons} & \\textbf{} & \\textbf{} & \\textbf{} & \\textbf{} & " \
             "\\textbf{} & \\textbf{} & \\textbf{}\\\\\n" \
             "        \\hline\n"

# 遍历数据列表并生成表格行
for i, row in enumerate(data):
    latex_code += f"        {i+1} & {' & '.join(map(str, row))} \\\\\n"
    latex_code += "        \\hline\n"

# 添加表格结尾
latex_code += "    \\end{tabular}\n" \
              "    \\caption{SLNN, N = 7, normalized absolute weights}\n" \
              "\\end{table}"

# 输出 LaTeX 代码
print(latex_code)


\begin{table}[htbp]
    \centering
    \begin{tabular}{|c|c|c|c|c|c|c|c|}
        \hline
        \textbf{Input Layer Neurons} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{}\\
        \hline
        1 & 0.5807 & 0.0 & 0.7195 & -0.5115 & -0.1748 & 0.7038 & -0.1317 \\
        \hline
        2 & 0.1696 & 0.0 & -0.0854 & 0.7659 & -0.4676 & 0.719 & 0.343 \\
        \hline
        3 & 0.0835 & 0.0884 & 0.1289 & -0.2663 & -1.1143 & -0.3482 & 0.3153 \\
        \hline
        4 & 0.497 & 0.0 & -0.4501 & 0.0 & -0.3754 & 0.0885 & -0.8998 \\
        \hline
        5 & 0.0 & 1.2054 & 0.1353 & 0.1299 & -0.1366 & 0.0732 & -0.0926 \\
        \hline
        6 & 0.6529 & 0.0 & 0.6603 & 0.608 & -0.0896 & -0.5479 & 0.0 \\
        \hline
        7 & -0.6563 & -0.0928 & 0.5427 & 0.294 & -0.3917 & 0.2601 & -0.624 \\
        \hline
    \end{tabular}
    \caption{SLNN, N = 7, normalized absolute weights}
\end{table}
