In [1]:
import torch

# Original matrix provided by the user
matrix = torch.tensor([[1, 1, 1, 1, 0, 1, 1],
                         [0, 0, 1, 0, 1, 0, 1],
                         [1, 1, 1, 1, 1, 1, 1],
                         [1, 1, 1, 0, 1, 1, 1],
                         [1, 1, 1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1, 1, 1],], dtype=torch.int)


# Compute the transpose of the matrix
transposed_matrix = matrix.t()

transposed_matrix


tensor([[1, 0, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 0, 1, 1, 1],
        [0, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [13]:
import numpy as np

# Define dimensions
k, n = 10, 26
r = n - k

# Construct G
G_identity = np.eye(k, dtype=int)
G_parity = np.random.randint(0, 2, size=(k, r))
G = np.hstack((G_identity, G_parity))

# # Construct H by finding nullspace of G
# H = np.linalg.null_space(G.T)

G


(array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
         1, 1, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
         1, 0, 1, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
         0, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
         0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
         1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
         0, 1, 0, 1]]),
 tensor([[1., 0., 1., 0., 0.

In [6]:
import torch
threshold = 9
# modified_model_pth = f"Hamming74/Result/Model/SLNN_decrease_hidden.weight_cpu/SLNN_model_hiddenlayer{threshold}_BER0.pth"
modified_model_pth = f"Hamming74/Result/Model/SLNN_decrease_con_cpu_hidden.weight/SLNN_model_deleted{threshold}_BER0.pth"
print("modified model:", torch.load(modified_model_pth))

modified model: OrderedDict([('hidden.weight', tensor([[ 5.6080e-01,  0.0000e+00,  6.2028e-01, -5.2675e-01, -8.5875e-02,
          6.3167e-01, -8.4146e-02],
        [ 5.7975e-02,  0.0000e+00,  0.0000e+00,  6.4106e-01, -4.7905e-01,
          5.9711e-01,  4.2571e-01],
        [ 5.4076e-02,  1.0758e-01,  1.0775e-01, -4.3751e-01, -9.7122e-01,
         -4.6573e-01,  4.1221e-01],
        [ 5.4778e-01,  0.0000e+00, -5.8159e-01,  0.0000e+00, -4.4671e-01,
          7.7618e-02, -6.3967e-01],
        [ 0.0000e+00,  1.2199e+00,  1.1140e-02,  2.6983e-02, -7.9629e-02,
          2.8661e-02, -5.5795e-02],
        [ 6.0561e-01,  0.0000e+00,  6.2137e-01,  5.8401e-01, -5.1537e-04,
         -5.7128e-01,  0.0000e+00],
        [-6.1606e-01,  0.0000e+00,  5.5149e-01,  1.4149e-01, -3.8065e-01,
          6.2549e-02, -7.1580e-01]])), ('hidden.bias', tensor([2.4704, 2.4747, 2.5994, 2.4471, 2.4412, 2.3569, 2.6469])), ('output.weight', tensor([[-1.0056, -1.1689,  1.0308,  0.9206, -1.0917, -0.7796,  0.8990],
      

In [42]:
import torch

# Your input tensor
input_tensor = torch.tensor([[ 0.0000,  0.0000,  0.7195,  0.0000,  0.0000,  0.7038,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.7659,  0.0000,  0.7190,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -1.1143,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.8998],
        [ 0.0000,  1.2054,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.6529,  0.0000,  0.6603,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.6563,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

# Apply thresholding operation
output_tensor = torch.where(input_tensor != 0, torch.tensor(1), torch.tensor(0))
print(output_tensor)

tensor([[0, 0, 1, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]])


In [1]:
import torch

# 定义张量
tensor = torch.tensor([
        2.2347e-01, 0.0000e+00, 2.4717e-01, 2.0990e-01, 3.4220e-02, 2.5171e-01,
         3.3531e-02,
        2.6341e-02, 0.0000e+00, 0.0000e+00, 2.9127e-01, 2.1766e-01, 2.7130e-01,
         1.9343e-01,
        2.1156e-02, 4.2089e-02, 4.2153e-02, 1.7117e-01, 3.7997e-01, 1.8220e-01,
         1.6127e-01,
        2.3885e-01, 0.0000e+00, 2.5360e-01, 0.0000e+00, 1.9478e-01, 3.3845e-02,
         2.7892e-01,
        0.0000e+00, 8.5781e-01, 7.8333e-03, 1.8974e-02, 5.5994e-02, 2.0154e-02,
         3.9235e-02,
        2.5416e-01, 0.0000e+00, 2.6077e-01, 2.4509e-01, 2.1629e-04, 2.3975e-01,
         0.0000e+00,
        2.4962e-01, 0.0000e+00, 2.2345e-01, 5.7328e-02, 1.5423e-01, 2.5344e-02,
         2.9003e-01
])

sorted_tensor, indices = tensor.sort()

sorted_tensor

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 2.1629e-04, 7.8333e-03, 1.8974e-02,
        2.0154e-02, 2.1156e-02, 2.5344e-02, 2.6341e-02, 3.3531e-02, 3.3845e-02,
        3.4220e-02, 3.9235e-02, 4.2089e-02, 4.2153e-02, 5.5994e-02, 5.7328e-02,
        1.5423e-01, 1.6127e-01, 1.7117e-01, 1.8220e-01, 1.9343e-01, 1.9478e-01,
        2.0990e-01, 2.1766e-01, 2.2345e-01, 2.2347e-01, 2.3885e-01, 2.3975e-01,
        2.4509e-01, 2.4717e-01, 2.4962e-01, 2.5171e-01, 2.5360e-01, 2.5416e-01,
        2.6077e-01, 2.7130e-01, 2.7892e-01, 2.9003e-01, 2.9127e-01, 3.7997e-01,
        8.5781e-01])

In [11]:
# 数据列表
data = [[ 0.5807,  0.0000,  0.7195, -0.5115, -0.1748,  0.7038, -0.1317],
        [ 0.1696,  0.0000, -0.0854,  0.7659, -0.4676,  0.7190,  0.3430],
        [ 0.0835,  0.0884,  0.1289, -0.2663, -1.1143, -0.3482,  0.3153],
        [ 0.4970,  0.0000, -0.4501,  0.0000, -0.3754,  0.0885, -0.8998],
        [ 0.0000,  1.2054,  0.1353,  0.1299, -0.1366,  0.0732, -0.0926],
        [ 0.6529,  0.0000,  0.6603,  0.6080, -0.0896, -0.5479,  0.0000],
        [-0.6563, -0.0928,  0.5427,  0.2940, -0.3917,  0.2601, -0.6240]]

# 生成 LaTeX 代码
latex_code = "\\begin{table}[htbp]\n" \
             "    \\centering\n" \
             "    \\begin{tabular}{|c|c|c|c|c|c|c|c|}\n" \
             "        \\hline\n" \
             "        \\textbf{Input Layer Neurons} & \\textbf{} & \\textbf{} & \\textbf{} & \\textbf{} & " \
             "\\textbf{} & \\textbf{} & \\textbf{}\\\\\n" \
             "        \\hline\n"

# 遍历数据列表并生成表格行
for i, row in enumerate(data):
    latex_code += f"        {i+1} & {' & '.join(map(str, row))} \\\\\n"
    latex_code += "        \\hline\n"

# 添加表格结尾
latex_code += "    \\end{tabular}\n" \
              "    \\caption{SLNN, N = 7, normalized absolute weights}\n" \
              "\\end{table}"

# 输出 LaTeX 代码
print(latex_code)


\begin{table}[htbp]
    \centering
    \begin{tabular}{|c|c|c|c|c|c|c|c|}
        \hline
        \textbf{Input Layer Neurons} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{}\\
        \hline
        1 & 0.5807 & 0.0 & 0.7195 & -0.5115 & -0.1748 & 0.7038 & -0.1317 \\
        \hline
        2 & 0.1696 & 0.0 & -0.0854 & 0.7659 & -0.4676 & 0.719 & 0.343 \\
        \hline
        3 & 0.0835 & 0.0884 & 0.1289 & -0.2663 & -1.1143 & -0.3482 & 0.3153 \\
        \hline
        4 & 0.497 & 0.0 & -0.4501 & 0.0 & -0.3754 & 0.0885 & -0.8998 \\
        \hline
        5 & 0.0 & 1.2054 & 0.1353 & 0.1299 & -0.1366 & 0.0732 & -0.0926 \\
        \hline
        6 & 0.6529 & 0.0 & 0.6603 & 0.608 & -0.0896 & -0.5479 & 0.0 \\
        \hline
        7 & -0.6563 & -0.0928 & 0.5427 & 0.294 & -0.3917 & 0.2601 & -0.624 \\
        \hline
    \end{tabular}
    \caption{SLNN, N = 7, normalized absolute weights}
\end{table}
