In [1]:
import torch

# Original matrix provided by the user
matrix = torch.tensor([
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0],
[0, 1, 0, 0, 0, 0, 0, 0 ,0 ,0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1],
[0, 0, 1, 0, 0, 0, 0, 0, 0 ,0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1],
[0, 0, 0, 1, 0, 0, 0, 0 ,0 ,0, 0 ,0, 1, 0, 1, 0, 0, 0, 0 ,0 ,1 ,1 ,0 ,1 ,1 ,0 ,1, 1, 1, 0, 1, 0, 1, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0],
[0, 0, 0 ,0, 0, 1, 0, 0 ,0 ,0 ,0, 0 ,1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ,1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1 ,0 ,1 ,0 ,1 ,1 ,1 ,0 ,1 ,1 ,1],
[0, 0, 0, 0 ,0, 0, 0, 1 ,0 ,0 ,0 ,0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0 ,1 ,1, 1, 1, 0, 0 ,1 ,0 ,0, 0, 1, 1, 0],
[0, 0, 0, 0, 0 ,0, 0, 0 ,0 ,1 ,0 ,0 ,1 ,1 ,1, 0, 0, 0, 0 ,1 ,1 ,0 ,0 ,0 ,1 ,1 ,0, 1, 1, 1, 0, 1 ,0, 0],
[0, 0, 0, 0, 0, 0, 0, 0 ,0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1 ,1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0 ,0, 0 ,0 ,0 ,0 ,1 ,0 ,1 ,0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1],
], dtype=torch.int)


# Compute the transpose of the matrix
transposed_matrix = matrix.t()

transposed_matrix


tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        [1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1],
        [1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 1

In [13]:
import numpy as np

# Define dimensions
k, n = 10, 26
r = n - k

# Construct G
G_identity = np.eye(k, dtype=int)
G_parity = np.random.randint(0, 2, size=(k, r))
G = np.hstack((G_identity, G_parity))

# # Construct H by finding nullspace of G
# H = np.linalg.null_space(G.T)

G


(array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
         1, 1, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
         1, 0, 1, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
         0, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
         0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
         1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
         0, 1, 0, 1]]),
 tensor([[1., 0., 1., 0., 0.

In [15]:
import torch
bits = 10
encoded = 26
test1 = 10 * torch.log10(torch.tensor(bits / encoded, dtype=torch.float)) 
test1 = test1 - torch.tensor(10/26)

print("test1", test1)

test1 tensor(-4.5343)


In [16]:
import bchlib
help(bchlib)

Help on module BCH:

NAME
    BCH - BCH Library

CLASSES
    builtins.object
        bchlib.BCH
    
    class BCH(builtins.object)
     |  BCH Encoder/Decoder
     |  
     |  __init__(t, poly=None, m=None, swap_bits=False) → bch
     |      Constructor creates a BCH object with given 't' bit strength.  At
     |      least one of 'poly' and/or 'm' must be provided.  If 'poly' is
     |      provided but 'm' (Galois field order) is not, 'm' will be
     |      calculated automatically.  If 'm' between 5 and 15 inclusive is'
     |      provided, 'polywill be selected automatically.  The 'swap_bits'
     |      parameter will reverse the bit order within data and syndrome
     |      bytes.
     |  
     |  Methods defined here:
     |  
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |  
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  compute_even_syn(...)
     |

In [2]:
import torch

# Your first tensor
tensor1 = torch.tensor([[0.1582, 0.2170, 0.1495, 0.3974, 0.4741, 0.2054, 0.7275],
                        [0.8117, 0.4013, 0.1386, 0.2082, 0.2137, 0.1977, 0.0406]])

# Your second tensor, which seems to be intended as a per-column property
tensor2 = torch.tensor([2.3291, 2.0119])

# Reshape tensor2 from [2] to [1, 2] for proper broadcasting
tensor2_reshaped = tensor2.view(1, -1)

# Broadcast tensor2 across the rows of tensor1 and perform element-wise division
# Note: tensor1 needs to be divided in a manner that matches your description, which seems to have a misunderstanding.
# If you intend to divide each column by a single value, tensor2 should represent a value per column, not per row.
# Assuming a correction, where tensor2 represents column-wise properties and has shape [7], here's a corrected approach:

# Corrected tensor2 for column-wise properties
# tensor2_corrected = torch.tensor([2.3291, 2.0119])  # Placeholder, replace with actual column-wise values

# Perform the division
result = tensor1 / tensor2_reshaped

print("Resulting Tensor:\n", result)


RuntimeError: The size of tensor a (7) must match the size of tensor b (2) at non-singleton dimension 1