In [1]:
import torch

# Original matrix provided by the user
matrix = torch.tensor([[1, 1, 0, 1],
                                          [1, 0, 1, 1],
                                          [1, 0, 0, 0],
                                          [0, 1, 1, 1],
                                          [0, 1, 0, 0],
                                          [0, 0, 1, 0],
                                          [0, 0, 0, 1]], dtype=torch.int)


# Compute the transpose of the matrix
transposed_matrix = matrix.t()

transposed_matrix


tensor([[1, 1, 1, 0, 0, 0, 0],
        [1, 0, 0, 1, 1, 0, 0],
        [0, 1, 0, 1, 0, 1, 0],
        [1, 1, 0, 1, 0, 0, 1]], dtype=torch.int32)

In [ ]:
matrix = torch.tensor([[1, 1, 0, 1],
                      [1, 0, 1, 1],
                      [1, 0, 0, 0],
                      [0, 1, 1, 1],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]], dtype=torch.int)
# Number of rows and columns in G
n, k = matrix.shape

# Create an identity matrix of size n-k x n-k, and append it to a zero matrix of size n-k x k
# to form the basic structure of H. This step needs to be adjusted based on the specific requirements
# and properties of the provided G matrix, as the direct approach might not apply.
# Here, we're creating a simple placeholder for H to illustrate the approach.
# This will not directly result in a valid H for the provided G without further adjustments.

# Determine the size for the parity part (n-k) and message part (k) based on G's structure
# Assuming n = 7 (from the structure of G), but we need to define k correctly based on your specific code structure.
# For the sake of an example, we'll proceed with a placeholder approach.

# This is a simplified and not directly applicable method since the exact structure and properties of G
# (like whether it's systematic or not) are not entirely clear from the question.
# Adjustments based on the specific code and its properties are necessary.

# Placeholder H matrix generation (illustrative and needs adjustment)
H = torch.zeros((n-k, n), dtype=torch.float)
H[:, k:] = torch.eye(n-k)

# Print the placeholder H matrix (this is not the final H for the provided G without further adjustments)
print(H)

In [ ]:
import torch
order = 10
# modified_model_pth = f"Hamming74/Result/Model/SLNN_decrease_hidden.weight_cpu/SLNN_model_hiddenlayer{threshold}_BER0.pth"
modified_model_pth = "Hamming74/Result/Model/SLNN_edgedeleted43_output.weight_cpu/SLNN7_edgedeleted43_order55.pth"
print("modified model:", torch.load(modified_model_pth))

In [42]:
import torch

# Your input tensor
input_tensor = torch.tensor([[ 0.0000,  0.0000,  0.7195,  0.0000,  0.0000,  0.7038,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.7659,  0.0000,  0.7190,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -1.1143,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.8998],
        [ 0.0000,  1.2054,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.6529,  0.0000,  0.6603,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.6563,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

# Apply thresholding operation
output_tensor = torch.where(input_tensor != 0, torch.tensor(1), torch.tensor(0))
print(output_tensor)

tensor([[0, 0, 1, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]])


In [6]:
import torch

# 定义张量
tensor = torch.tensor(
    [0.1238, 0.1448, 0.1637, 0.1490, 0.1587, 0.1085, 0.1515,
        0.1369, 0.1183, 0.1619, 0.1586, 0.1598, 0.1078, 0.1567,
        0.1310, 0.1190, 0.1678, 0.1502, 0.1563, 0.1185, 0.1572,
        0.1337, 0.1403, 0.1611, 0.1539, 0.1502, 0.1129, 0.1480,
        0.1266, 0.1135, 0.1823, 0.1553, 0.1538, 0.1127, 0.1558,
        0.1240, 0.1415, 0.1696, 0.1538, 0.1533, 0.1102, 0.1476,
        0.1261, 0.1356, 0.1779, 0.1461, 0.1490, 0.1142, 0.1510,
        0.1255, 0.1149, 0.1784, 0.1604, 0.1534, 0.1151, 0.1523,
        0.1218, 0.1400, 0.1565, 0.1473, 0.1423, 0.1471, 0.1451,
        0.1303, 0.1165, 0.1582, 0.1541, 0.1452, 0.1489, 0.1468,
        0.1247, 0.1202, 0.1606, 0.1487, 0.1479, 0.1435, 0.1544,
        0.1281, 0.1388, 0.1555, 0.1509, 0.1461, 0.1379, 0.1427,
        0.1269, 0.1130, 0.1711, 0.1450, 0.1505, 0.1469, 0.1467,
        0.1210, 0.1327, 0.1669, 0.1475, 0.1435, 0.1439, 0.1444,
        0.1242, 0.1407, 0.1674, 0.1389, 0.1480, 0.1383, 0.1426,
        0.1211, 0.1153, 0.1742, 0.1522, 0.1529, 0.1365, 0.1478])

sorted_tensor, indices = tensor.sort()

sorted_tensor

tensor([0.1078, 0.1085, 0.1102, 0.1127, 0.1129, 0.1130, 0.1135, 0.1142, 0.1149,
        0.1151, 0.1153, 0.1165, 0.1183, 0.1185, 0.1190, 0.1202, 0.1210, 0.1211,
        0.1218, 0.1238, 0.1240, 0.1242, 0.1247, 0.1255, 0.1261, 0.1266, 0.1269,
        0.1281, 0.1303, 0.1310, 0.1327, 0.1337, 0.1356, 0.1365, 0.1369, 0.1379,
        0.1383, 0.1388, 0.1389, 0.1400, 0.1403, 0.1407, 0.1415, 0.1423, 0.1426,
        0.1427, 0.1435, 0.1435, 0.1439, 0.1444, 0.1448, 0.1450, 0.1451, 0.1452,
        0.1461, 0.1461, 0.1467, 0.1468, 0.1469, 0.1471, 0.1473, 0.1475, 0.1476,
        0.1478, 0.1479, 0.1480, 0.1480, 0.1487, 0.1489, 0.1490, 0.1490, 0.1502,
        0.1502, 0.1505, 0.1509, 0.1510, 0.1515, 0.1522, 0.1523, 0.1529, 0.1533,
        0.1534, 0.1538, 0.1538, 0.1539, 0.1541, 0.1544, 0.1553, 0.1555, 0.1558,
        0.1563, 0.1565, 0.1567, 0.1572, 0.1582, 0.1586, 0.1587, 0.1598, 0.1604,
        0.1606, 0.1611, 0.1619, 0.1637, 0.1669, 0.1674, 0.1678, 0.1696, 0.1711,
        0.1742, 0.1779, 0.1784, 0.1823])

In [11]:
# 数据列表
data = [[ 0.5807,  0.0000,  0.7195, -0.5115, -0.1748,  0.7038, -0.1317],
        [ 0.1696,  0.0000, -0.0854,  0.7659, -0.4676,  0.7190,  0.3430],
        [ 0.0835,  0.0884,  0.1289, -0.2663, -1.1143, -0.3482,  0.3153],
        [ 0.4970,  0.0000, -0.4501,  0.0000, -0.3754,  0.0885, -0.8998],
        [ 0.0000,  1.2054,  0.1353,  0.1299, -0.1366,  0.0732, -0.0926],
        [ 0.6529,  0.0000,  0.6603,  0.6080, -0.0896, -0.5479,  0.0000],
        [-0.6563, -0.0928,  0.5427,  0.2940, -0.3917,  0.2601, -0.6240]]

# 生成 LaTeX 代码
latex_code = "\\begin{table}[htbp]\n" \
             "    \\centering\n" \
             "    \\begin{tabular}{|c|c|c|c|c|c|c|c|}\n" \
             "        \\hline\n" \
             "        \\textbf{Input Layer Neurons} & \\textbf{} & \\textbf{} & \\textbf{} & \\textbf{} & " \
             "\\textbf{} & \\textbf{} & \\textbf{}\\\\\n" \
             "        \\hline\n"

# 遍历数据列表并生成表格行
for i, row in enumerate(data):
    latex_code += f"        {i+1} & {' & '.join(map(str, row))} \\\\\n"
    latex_code += "        \\hline\n"

# 添加表格结尾
latex_code += "    \\end{tabular}\n" \
              "    \\caption{SLNN, N = 7, normalized absolute weights}\n" \
              "\\end{table}"

# 输出 LaTeX 代码
print(latex_code)


\begin{table}[htbp]
    \centering
    \begin{tabular}{|c|c|c|c|c|c|c|c|}
        \hline
        \textbf{Input Layer Neurons} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{} & \textbf{}\\
        \hline
        1 & 0.5807 & 0.0 & 0.7195 & -0.5115 & -0.1748 & 0.7038 & -0.1317 \\
        \hline
        2 & 0.1696 & 0.0 & -0.0854 & 0.7659 & -0.4676 & 0.719 & 0.343 \\
        \hline
        3 & 0.0835 & 0.0884 & 0.1289 & -0.2663 & -1.1143 & -0.3482 & 0.3153 \\
        \hline
        4 & 0.497 & 0.0 & -0.4501 & 0.0 & -0.3754 & 0.0885 & -0.8998 \\
        \hline
        5 & 0.0 & 1.2054 & 0.1353 & 0.1299 & -0.1366 & 0.0732 & -0.0926 \\
        \hline
        6 & 0.6529 & 0.0 & 0.6603 & 0.608 & -0.0896 & -0.5479 & 0.0 \\
        \hline
        7 & -0.6563 & -0.0928 & 0.5427 & 0.294 & -0.3917 & 0.2601 & -0.624 \\
        \hline
    \end{tabular}
    \caption{SLNN, N = 7, normalized absolute weights}
\end{table}


In [2]:
import torch
order = torch.arange(1, 8, 1).to(torch.int)

snr = [0, 8]
for i in range(len(snr)):
    print("snr", snr[i])

    for j in range(len(order)):
        print("order", order[j])

snr 0
order tensor(1, dtype=torch.int32)
order tensor(2, dtype=torch.int32)
order tensor(3, dtype=torch.int32)
order tensor(4, dtype=torch.int32)
order tensor(5, dtype=torch.int32)
order tensor(6, dtype=torch.int32)
order tensor(7, dtype=torch.int32)
snr 8
order tensor(1, dtype=torch.int32)
order tensor(2, dtype=torch.int32)
order tensor(3, dtype=torch.int32)
order tensor(4, dtype=torch.int32)
order tensor(5, dtype=torch.int32)
order tensor(6, dtype=torch.int32)
order tensor(7, dtype=torch.int32)


In [1]:
import torch

# Example parity check matrix H
H = torch.tensor([[1, 1, 1, 0, 0, 0],
                  [0, 0, 0, 1, 1, 1],
                  [1, 0, 0, 1, 0, 0],
                  [0, 1, 0, 0, 1, 0],
                  [0, 0, 1, 0, 0, 1]], dtype=torch.float)

# Find the null space of H to get the generator matrix G
# This involves finding the solutions to Hx = 0

# Using SVD (Singular Value Decomposition) to find the null space
u, s, v = torch.svd(H)

# The null space is spanned by the columns of V corresponding to zero singular values in S
# In practice, due to numerical precision, we consider singular values close to zero as zero
tolerance = 1e-5
null_mask = (s < tolerance).nonzero(as_tuple=True)[0]
G = v[:, null_mask]

# Since G is derived from the V matrix of SVD, its columns span the null space
# Transpose G to get the standard form (rows are codewords)
G = G.t()

print("Generator matrix G:")
print(G)


Generator matrix G:
tensor([[-0.1848,  0.5661, -0.3813,  0.1848, -0.5661,  0.3813]])


In [4]:
import matlab.engine
def test(input):
    eng = matlab.engine.start_matlab()
    output = eng.sqrt(input)
    eng.quit()
    return output

4.0


In [2]:
import galois

# Initialize your BCH code
bch = galois.BCH(255, 239)
print(bch.H.shape)

# # Convert the generator polynomial to a list of integers (for compatibility with the join method)
# # and then convert each integer to a string.
# generator_polynomial_as_strings = list(map(str, bch.G))
# 
# # Join the string representations with commas to create a single string that is CSV-friendly
# csv_content = ','.join(generator_polynomial_as_strings)
# 
# # Write the CSV content to a file
# with open('BCH255_239.csv', 'w') as file:
#     file.write(csv_content)

(16, 255)


In [4]:
import numpy as np
data = np.loadtxt('BCH255_239.csv', delimiter=',')

ValueError: could not convert string '[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0' to float64 at row 0, column 1.

In [4]:
import torch

def generate_binary_codebook(batch_size, num_bits):
    # Ensure that `batch_size` numbers are represented in `num_bits` binary format
    binary_codebook = torch.zeros((batch_size, num_bits), dtype=torch.uint8)
    
    # Generate numbers and expand dimensions for binary conversion
    numbers = torch.arange(batch_size).unsqueeze(-1)
    
    # Convert to binary representation
    for i in range(num_bits):
        binary_codebook[:, num_bits - 1 - i] = (numbers >> i) & 1
    
    return binary_codebook

# Example usage:
num_bits = 10  # Smaller number of bits for demonstration
batch_size = 1024  # Number of binary codes to generate
binary_codebook = generate_binary_codebook(batch_size, num_bits)
print(binary_codebook)


RuntimeError: expand(torch.LongTensor{[1024, 1]}, size=[1024]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)