In [19]:
import torch

# Original matrix provided by the user
matrix = torch.tensor([[1,	0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	1,	0,	1,	1,	0,	1,	0],
[0, 1,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	1,	0,	1,	0,	1,	0,	1, 1],
[0, 0,	1,	0,	0,	0,	0,	0,	0,	0,	1,	1,	0,	0,	1,	0,	1,	1,	1, 0],
[0, 0,	0,	1,	0,	0,	0,	0,	0,	0,	1,	0,	1,	1,	0,	0,	0,	0,	1, 1],
[0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	1,	0,	1,	1,	1,	1,	1,	1,	0, 0],
[0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	1,	1,	1,	1,	1,	1,	1,	0,	1, 1],
[0,	0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	1,	0,	1,	1,	0,	1,	0, 0],
[0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0,	1,	1,	1,	1,	0,	0,	1,	1,	1],
[0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	1,	1,	0,	0,	0,	1,	0,	1,	1,	0],
[0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	1,	0,	0,	0,	1,	1,	1,	0,	1]], dtype=torch.int)

# Compute the transpose of the matrix
transposed_matrix = matrix.t()

transposed_matrix


tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
        [0, 1, 0, 1, 1, 1, 1, 1, 0, 0],
        [1, 0, 0, 1, 1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
        [1, 0, 0, 0, 1, 1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1, 1, 0, 0, 0, 1],
        [0, 0, 1, 0, 1, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 1, 0, 1, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]], dtype=torch.int32)

In [13]:
import numpy as np

# Define dimensions
k, n = 10, 26
r = n - k

# Construct G
G_identity = np.eye(k, dtype=int)
G_parity = np.random.randint(0, 2, size=(k, r))
G = np.hstack((G_identity, G_parity))

# # Construct H by finding nullspace of G
# H = np.linalg.null_space(G.T)

G


(array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
         1, 1, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
         1, 0, 1, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
         0, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
         0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
         1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
         1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
         0, 1, 0, 1]]),
 tensor([[1., 0., 1., 0., 0.

In [15]:
import torch
bits = 10
encoded = 26
test1 = 10 * torch.log10(torch.tensor(bits / encoded, dtype=torch.float)) 
test1 = test1 - torch.tensor(10/26)

print("test1", test1)

test1 tensor(-4.5343)


In [16]:
import bchlib
help(bchlib)

Help on module BCH:

NAME
    BCH - BCH Library

CLASSES
    builtins.object
        bchlib.BCH
    
    class BCH(builtins.object)
     |  BCH Encoder/Decoder
     |  
     |  __init__(t, poly=None, m=None, swap_bits=False) → bch
     |      Constructor creates a BCH object with given 't' bit strength.  At
     |      least one of 'poly' and/or 'm' must be provided.  If 'poly' is
     |      provided but 'm' (Galois field order) is not, 'm' will be
     |      calculated automatically.  If 'm' between 5 and 15 inclusive is'
     |      provided, 'polywill be selected automatically.  The 'swap_bits'
     |      parameter will reverse the bit order within data and syndrome
     |      bytes.
     |  
     |  Methods defined here:
     |  
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |  
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  compute_even_syn(...)
     |

In [17]:
BCH = bchlib.BCH()
ecc = BCH.encode()


Could not connect to localhost: 57804
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 465, in start_client
    s.connect((host, port))
OSError: [Errno 65] No route to host
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers-pro/jupyter_debug/pydev_jupyter_utils.py", line 81, in attach_to_debugger
    debugger.connect(pydev_localhost.get_localhost(), debugger_port)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 670, in connect
    s = start_client(host, port)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 465, in start_client
    s.connect((host, port))
OSError: [Errno 65] No route to host
Failed to connect to target debugger.
